import { FeedItem } from '@/types';

export const mockSocialPosts: FeedItem[] = [
  {
    id: 'social-1',
    type: 'social',
    title: 'Just shipped a new feature 🚀',
    description:
      'We just launched real-time collaboration in our app. The team worked incredibly hard on this — massive shoutout to everyone involved!',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&auto=format&fit=crop',
    source: 'Twitter/X',
    username: '@devbuilder',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=devbuilder',
    hashtags: ['#buildinpublic', '#startup', '#tech'],
    likes: 1240,
    comments: 87,
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'social-2',
    type: 'social',
    title: 'AI is changing everything 🤖',
    description:
      "Three months ago I started using AI tools in my workflow. Productivity has increased by 3x. Here's what worked for me and what didn't...",
    image: undefined as any,
    source: 'Threads',
    username: '@aiexplorer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aiexplorer',
    hashtags: ['#AI', '#productivity', '#tech'],
    likes: 3891,
    comments: 204,
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'social-3',
    type: 'social',
    title: 'Open source or die 🔓',
    description:
      'Why I believe every developer should contribute to open source at least once a month. It completely changed my career trajectory.',
    image: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=600&auto=format&fit=crop',
    source: 'LinkedIn',
    username: '@opensourcedev',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=opensourcedev',
    hashtags: ['#opensource', '#developer', '#community'],
    likes: 892,
    comments: 56,
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'social-4',
    type: 'social',
    title: 'Next.js 15 is absolutely insane 🔥',
    description:
      'Just migrated a large project to Next.js 15 and the performance gains are wild. Server components + Turbopack is a game changer.',
    image: undefined as any,
    source: 'Twitter/X',
    username: '@nextjsfan',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nextjsfan',
    hashtags: ['#nextjs', '#webdev', '#react'],
    likes: 2147,
    comments: 143,
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'social-5',
    type: 'social',
    title: 'From 0 to $10k MRR in 6 months 💰',
    description:
      'I documented my entire journey building a SaaS product solo. No investors, no team — just code and persistence. Thread below 👇',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop',
    source: 'Twitter/X',
    username: '@indiehacker',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=indiehacker',
    hashtags: ['#indiehacker', '#saas', '#buildinpublic'],
    likes: 5230,
    comments: 312,
    publishedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'social-6',
    type: 'social',
    title: 'The future of design 🎨',
    description:
      'Design systems are no longer optional. Every serious product team needs one. Here is how we built ours from scratch in 30 days.',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&auto=format&fit=crop',
    source: 'LinkedIn',
    username: '@designlead',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=designlead',
    hashtags: ['#design', '#ux', '#productdesign'],
    likes: 1560,
    comments: 98,
    publishedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
];